config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resources :bands, only: [:index, :create, :new, :edit, :show, :update, :destroy]
  resources :albums, only: [:create, :new, :edit, :show, :update, :destroy]
  resources :tracks, only: [:new, :create, :edit, :show, :update, :destroy]

  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/bands')
end

app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, :live, presence: true

  belongs_to :band


  has_many :tracks,
  dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
  dependent: :destroy
end

app/models/note.rb
class Note < ApplicationRecord
  validates :text, :user_id, :track_id, presence: true

  belongs_to :user

  belongs_to :track
end

app/models/track.rb
class Track < ApplicationRecord
  validates :title, :ord, :bonus, presence: true

  belongs_to :album

  has_many :notes
end

app/models/user.rb
class User < ApplicationRecord
  attr_reader :password

  after_initialize :ensure_session_token

  validates :session_token, :email, :password_digest, presence: true
  validates :session_token, uniqueness: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save
    self.session_token
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    @user = User.find_by(email: email)
    return nil if @user.nil?
    if @user.valid_password?(password)
      return @user
    else
      return nil
    end
  end

  has_many :notes
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_log_in
  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def new
    render :new
  end

  def edit
  end

  def show
    @album ||= Album.find(params[:id])
  end

  def update
  end

  def destroy
  end

  private
  def album_params
    params.require(:album).permit(:band_id, :title, :year, :live)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def require_log_in
    redirect_to new_session_url if !logged_in?
  end

  def require_log_out
    redirect_to users_url if logged_in?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  before_action :require_log_in

  def index
    @bands = Band.all
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    if @band.destroy
      redirect_to bands_url
    end
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    note = current_user.notes.new(note_params)
    note.save
    flash[:errors] = note.errors.full_messages

    redirect_to track_url(note.track_id)
  end

  def destroy
    note = current_user.notes.find(params[:id])
    note.destroy
    redirect_to track_url(note.track_id)
  end

  private

  def note_params
    params.require(:note).permit(:body, :track_id)
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if user
      login!(user)
      redirect_to bands_url
    else
      flash[:errors] = ['wrong email or password']
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_log_in
  def new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def show
    @track = Track.find(params[:id])
  end

  def update
  end

  def destroy
  end

  private
  def track_params
    params.require(:track).permit(:title, :bonus, :album_id, :ord, :lyrics)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to bands_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
  def ugly_lyrics(lyrics)
    result = []
    lyrics = lyrics.dup
    until lyrics.dup.empty?
      result << lyrics[0...30]
      lyrics.slice!(0,30)
    end

    result.map do |i|
      "♫" + i
    end

    result.each do |result|
      "<p>#{result}</p>".html_safe
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

app/views/albums/destroy.html.erb
<h1>Albums#destroy</h1>
<p>Find me in app/views/albums/destroy.html.erb</p>

app/views/albums/edit.html.erb
<h1>Albums#edit</h1>
<p>Find me in app/views/albums/edit.html.erb</p>

app/views/albums/new.html.erb
<% if flash[:errors] %>
  <%= flash.now[:errors] %>
<% end %>

<form class ='newalbumform' action="<%= albums_url %>" method="post"  style="text-align: center">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <h1>New Album</h1>

  <label for="title"></label>
  <input id='title' type="text" name="album[title]" value="Album Name">

  <p>Artist:</p>
  <label for="albumband"></label>
  <select name="album[band_id]" id = 'albumband'>
    <option disabled selected>--select a band--</option>
    <% Band.all.each do |band| %>
      <option value=" <%= band.id %> "> <%=band.name%> </option>
    <% end %>
  </select>

  <br>
  <p>Year:</p>
  <label for="year"></label>
  <input id='year' type="number" name="album[year]" value="Year made">

  <p>Live?:</p>
  <label for="live"></label>
  <select name="album[live]" id = 'live'>
      <option value="<%=false%>"> No </option>
      <option value="<%=true%>"> Yes </option>
  </select>

  <br><br>
  <input type="submit" >
</form>

app/views/albums/show.html.erb
<section style="text-align: center" class='albuminfo'>
  <h1>ALBUM PAGE</h1>
  <p>Name: <%= @album.title %></p>
  <p>Band: <%= @album.band.name %></p>
  <p>Year: <%= @album.year %></p>
  <p>Live: <%= @album.live == true ? 'Yes' : 'No' %></p>
  <section class="tracklist">
    <p>Tracklist: </p>
    <% if @album.tracks %>
      <% @album.tracks.each do |track| %>
        <p>-<a href="/tracks/<%=track.id%>"><%= track.title %></a> </p>
      <% end %>
    <% else %>
      <p>No Tracks</p>
    <% end %>
  </section>

</section>

<div class="button1">
  <%= button_to "Go To Band Page", band_url(@album.band), method: :get, class: 'railsbutton' %>
  <br>
  <%= button_to "Add a track", new_track_url, method: :get, class: 'railsbutton' %>
</div>

app/views/albums/update.html.erb
<h1>Albums#update</h1>
<p>Find me in app/views/albums/update.html.erb</p>

app/views/bands/edit.html.erb
<% if flash[:errors] %>
  <%= flash.now[:errors] %>
<% end %>

<form class ='editbandform' action="<%= band_url(@band) %>" method="post" style="text-align: center">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <h1 style='font-size: 40px; text-decoration: underline'>New Band</h1>

  <label for="name">Enter band name:</label>
  <input id='name' type="text" name="band[name]" value="Band Name">

  <br><br>
  <input type="submit" >
</form>

app/views/bands/index.html.erb
<h1 class='bandlist' style='font-size: 40px; text-decoration: underline'>List of bands:</h1>

<% @bands.each do |band| %>
  <section class='bandsection'>
    <a href="<%= band_url(band.id) %> "><%= band.name %></a>
  </section>
<% end %>

<div class="createnewbandbutton" style='text-align: center'>
  <%= button_to "Create New Band", new_band_url, method: :get, class: 'railsbutton' %>
</div>

app/views/bands/new.html.erb
<% if flash[:errors] %>
  <%= flash.now[:errors] %>
<% end %>

<form class ='newbandform' action="<%= bands_url %>" method="post"  style="text-align: center">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <h1 style='font-size: 40px; text-decoration: underline'>New Band</h1>

  <label for="name">Enter band name:</label>
  <input id='name' type="text" name="band[name]" value="Band Name">

  <br><br>
  <input type="submit" >
</form>

app/views/bands/show.html.erb
<h1 style='font-size: 50px;' class='showbandheader'> <%= @band.name %> </h1>

<div style='text-align: center; margin-top: -30px'>
  <%= button_to "Create New Album", new_album_url, method: :get, class: 'railsbutton' %>
  <%= button_to "Edit Band", edit_band_url(@band), method: :get, class: 'railsbutton' %>
  <%= button_to "Delete Band", band_url(@band), method: :delete, class: 'railsbutton' %>
</div>

<% if @band.albums %>
  <h3 style='font-size: 40px; text-align: center; margin-top: 40px'>Albums:</h3>
<% else %>

<% end %>


<section style='text-align: center'>
  <% @band.albums.each do |album| %>
    <section class='albumarea'>
        <p><%= album.title %><%= button_to "Album Page", album_url(album), method: :get, class: 'railsbutton' %></p>
    </section>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  </head>

  <body>

    <container class='buttons'>
      <% if current_user %>
        <%= button_to "Log Out", session_url, method: :delete, class: 'railsbutton' %>
      <% else %>
        <%= link_to 'Sign In', new_session_url %>
        <%= link_to 'New User', new_user_url %>
      <% end %>
    </container>



    <section class='middle'>
      <h1 class='logo'><a href="/">Music App</a></h1>
      <hr class='titlehr'>
      <%= yield %>
    </section>


  </body>
</html>

app/views/notes/_note.html.erb
<div class='note-item'>
  <p><%= note.body %></p>
  <div class='note-item-info'>
    <p>Authored by: <%= note.user.email %></p>

    <% if note.user_id == current_user.id %>
      <form action="<%= note_url(note) %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
        <input type="submit" value="Destroy Note">
      </form>
    <% end %>
  </div>
</div>

app/views/tracks/create.html.erb
<h1>Tracks#create</h1>
<p>Find me in app/views/tracks/create.html.erb</p>

app/views/tracks/destroy.html.erb
<h1>Tracks#destroy</h1>
<p>Find me in app/views/tracks/destroy.html.erb</p>

app/views/tracks/edit.html.erb
<h1>Tracks#edit</h1>
<p>Find me in app/views/tracks/edit.html.erb</p>

app/views/tracks/new.html.erb
<% if flash[:errors] %>
  <%= flash.now[:errors] %>
<% end %>

<form class ='newtracksform' action="<%= tracks_url %>" method="post"  style="text-align: center">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <h1>New Track</h1>

  <label for="title"></label>
  <input id='title' type="text" name="track[title]" value="Track Name">

  <p>Album:</p>
  <label for="trackalbum"></label>
  <select name="track[album_id]" id = 'trackalbum'>
    <option disabled selected>--select an album--</option>
    <% Album.all.each do |album| %>
      <option value="<%= album.id %>"> <%=album.title%> </option>
    <% end %>
  </select>

  <p>Track #:</p>
  <label for="tracknum"></label>
  <input id='tracknum' type="number" name="track[ord]" value="Track #">

  <p>Bonus?:</p>
  <label for="bonus"></label>
  <select name="track[bonus]" id = 'bonus'>
      <option value="<%=false%>"> No </option>
      <option value="<%=true%>"> Yes </option>
  </select>

  <br>
  <br>
  <p>Lyrics:</p>
  <textarea name="track[lyrics]" rows="8" cols="40"></textarea>

  <br><br>
  <input type="submit" >
</form>

app/views/tracks/show.html.erb
<section style="text-align: center" class='trackinfo'>
  <h1 style='font-size: 30px; text-decoration: underline'>TRACK INFO</h1>
  <p>Title: <%= @track.title %></p>
  <p>Band: <%= @track.album.band.name %></p>
  <p>Album: <%= @track.album.title %></p>
  <p>Track #: <%= @track.ord %></p>
  <p>Bonus: <%= @track.bonus == true ? 'Yes' : 'No' %></p>
  <% if @track.lyrics %>
    <section class='uglylyrics'>
      <h1>Lyrics:</h1>
      <% ugly_lyrics(@track.lyrics).each do |lyric| %>
        <p>&#9835<%=lyric %></p>
      <% end %>
    </section>
  <% end %>
</section>

<div class="button1">
  <%= button_to "Go To Album Page", album_url(@track.album), method: :get, class: 'railsbutton' %>
  <%= button_to "Go To Band Page", band_url(@track.album.band), method: :get, class: 'railsbutton' %>
</div>

app/views/tracks/update.html.erb
<h1>Tracks#update</h1>
<p>Find me in app/views/tracks/update.html.erb</p>

app/views/users/new.html.erb
<% if flash[:errors] %>
  <%= flash.now[:errors] %>
<% end %>

<form class ='newuserform' action="<%= users_url %>" method="post">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <h1>New User</h1>

  <label for="email"></label>
  <input id='email' type="text" name="user[email]" value="E-mail address">
  <br><br>

  <label for="password"></label>
  <input id='password' type="password" name="user[password]" value="password">

  <br><br>
  <input type="submit">
</form>

app/views/users/show.html.erb
<h1>Hello</h1>